package ch.zuegi.rvmcp.domain.template

import ch.zuegi.rvmcp.domain.model.memory.Decision
import ch.zuegi.rvmcp.domain.model.requirement.Requirement
import ch.zuegi.rvmcp.domain.model.requirement.RequirementPriority
import ch.zuegi.rvmcp.domain.model.requirement.RequirementType
import ch.zuegi.rvmcp.domain.model.requirement.Stakeholder
import java.time.Instant

/**
 * Template for generating Requirements documents.
 *
 * Based on ADR-005: Kotlin String Templates
 */
object RequirementsTemplate {
    fun generate(
        projectName: String,
        summary: String,
        requirements: List<Requirement>,
        stakeholders: List<Stakeholder>,
        decisions: List<Decision>,
    ): String =
        """
        # Requirements: $projectName
        
        > **Generated:** ${Instant.now()}  
        > **Status:** Draft
        
        ---
        
        ## Executive Summary
        
        $summary
        
        ---
        
        ## Stakeholders
        
        ${renderStakeholders(stakeholders)}
        
        ---
        
        ## Requirements
        
        ### Must-Have Requirements
        
        ${renderRequirementsByPriority(requirements, RequirementPriority.MUST_HAVE)}
        
        ### Should-Have Requirements
        
        ${renderRequirementsByPriority(requirements, RequirementPriority.SHOULD_HAVE)}
        
        ### Could-Have Requirements
        
        ${renderRequirementsByPriority(requirements, RequirementPriority.COULD_HAVE)}
        
        ---
        
        ## Functional Requirements
        
        ${renderRequirementsByType(requirements, RequirementType.FUNCTIONAL)}
        
        ## Non-Functional Requirements
        
        ${renderRequirementsByType(requirements, RequirementType.NON_FUNCTIONAL)}
        
        ---
        
        ## Architectural Decisions
        
        ${renderDecisions(decisions)}
        
        ---
        
        ## Related Documents
        
        - [Architecture Design](architecture.md)
        - [Feature Specifications](features.md)
        - [User Stories](user-stories.md)
        
        ---
        
        *This document was automatically generated by Responsible Vibe Engineering MCP*
        """.trimIndent()

    private fun renderStakeholders(stakeholders: List<Stakeholder>): String {
        if (stakeholders.isEmpty()) return "*No stakeholders defined yet*"

        return stakeholders.joinToString("\n\n") { stakeholder ->
            """
            ### ${stakeholder.role}: ${stakeholder.name}
            ${if (stakeholder.email != null) "**Email:** ${stakeholder.email}" else ""}
            
            ${if (stakeholder.responsibilities.isNotEmpty()) {
                """
                **Responsibilities:**
                ${stakeholder.responsibilities.joinToString("\n") { "- $it" }}
                """.trimIndent()
            } else {
                ""
            }}
            """.trimIndent()
        }
    }

    private fun renderRequirementsByPriority(
        requirements: List<Requirement>,
        priority: RequirementPriority,
    ): String {
        val filtered = requirements.filter { it.priority == priority }

        if (filtered.isEmpty()) {
            return "*No ${priority.name.lowercase().replace('_', ' ')} requirements*"
        }

        return filtered.joinToString("\n\n") { req ->
            """
            #### ${req.id}: ${req.title}
            
            ${req.description}
            
            ${if (req.acceptanceCriteria.isNotEmpty()) {
                """
                **Acceptance Criteria:**
                ${req.acceptanceCriteria.joinToString("\n") { "- $it" }}
                """.trimIndent()
            } else {
                ""
            }}
            """.trimIndent()
        }
    }

    private fun renderRequirementsByType(
        requirements: List<Requirement>,
        type: RequirementType,
    ): String {
        val filtered = requirements.filter { it.type == type }

        if (filtered.isEmpty()) {
            return "*No ${type.name.lowercase().replace('_', ' ')} requirements*"
        }

        return filtered.joinToString("\n\n") { req ->
            """
            ### ${req.id}: ${req.title}
            
            **Priority:** ${req.priority.name.replace('_', ' ')}
            
            ${req.description}
            
            ${if (req.acceptanceCriteria.isNotEmpty()) {
                """
                **Acceptance Criteria:**
                ${req.acceptanceCriteria.joinToString("\n") { "- $it" }}
                """.trimIndent()
            } else {
                ""
            }}
            """.trimIndent()
        }
    }

    private fun renderDecisions(decisions: List<Decision>): String {
        if (decisions.isEmpty()) return "*No architectural decisions documented yet*"

        return decisions.joinToString("\n\n") { decision ->
            """
            ### Decision: ${decision.decision}
            
            **Phase:** ${decision.phase}  
            **Date:** ${decision.date}
            
            **Reasoning:**  
            ${decision.reasoning}
            """.trimIndent()
        }
    }
}
